In [1]:
import pandas as pd
import re, csv, nltk, string
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

data=pd.read_csv("dataset_balance.csv")
label_bullying=data['label_bullying']
text = data['text_message']
list_text=text.tolist()

In [2]:
data

label_bullying                                       text_message
0                  0  yeah I got 2 backups for all that. I just hate...
1                  0  I hate using my BB  but love my iPhone. Haven'...
2                  0      wow lol sounds like a lot of piss then hehehe
3                  0  not a damn thang..the typical rap beef. one pe...
4                  0  well damn!! where have you been when i have ne...
5                  0  watching without a trace too...hate when i mis...
6                  0  which they do most of the time:-P I don't hate...
7                  0                    haha fuck i wish i was there :(
8                  0  paranoid is wack as fuck...the best song on 80...
9                  0  in London  I hate thee :( ENJOY YOURSELVES!!! ...
10                 0  lollipop lolipop...oh loli loli loli....duh du...
11                 0  You pretty sure Angel's ass is fake too huh? I...
12                 0                      I hear that. I hate charging.
13                 0  That sucks. My furnace started making funny no...
14                 0                            DAMN STRAIGHT\r\n9na :)
15                 0                               I hate your job too.
16                 0  LOL! I'm not proud of my inability to deal wit...
17                 0  I hate upping more than downing lol @seanzagee...
18                 0            Awesome :) I hate updating the BIOS LOL
19                 0  Looks like a good competitor :) Wouldn't touch...
20                 0  ok that sucks. Someone needs to remind them ab...
21                 0                  Omg that sucks  but it's SO funny
22                 0  lol  i know what you mean. But i kinda am a ne...
23                 0                  I hate that bands have wardrobes.
24                 0               that sucks dude  sorry for your loss
25                 0  okay cool.  I can help you guys this weekend. ...
26                 0  i hate when shows take holiday breaks. its kil...
27                 0                     I'm such a pizza freak... Mmm.
28                 0  Oh honey  just hold in your mind the rankest t...
29                 0  ...okay. Maybe ONE more thing to look at on th...
...              ...                                                ...
8462               1  i did not donate but each time you say this sa...
8463               1  and i thought dem s put up their presidential ...
8464               1  disqus you cnn censor my disqus a little more ...
8465               1  dude ass den wen he came to wit that lame ass ...
8466               1  then why do you continue to watch it if you ar...
8467               1                  you are just wonderful and stupid
8468               1               eat a dick you nerdy looking bastard
8469               1  he did not do anything to take away guns even ...
8470               1  go back to your nerd table better yet a shallo...
8471               1                                   you are an idiot
8472               1  i have no fucking problem tell a dumbacking da...
8473               1  you are a poor excuse for a human and one of t...
8474               1  garbage overload stop it peasemold you are con...
8475               1                          you are all losers f yall
8476               1                          you are also stupid geesh
8477               1  you are a frightened infant who never saw comb...
8478               1  i am so tired of some people cramming their re...
8479               1  you are an idiot romney is not going to give s...
8480               1  no people have a right to speak no matter how ...
8481               1  you are a first class idiot there should be a ...
8482               1                    hahahahahahahahah he is a loser
8483               1  kingfisher come on name the lies you tool you ...
8484               1  yeah you pussy with your team jordan track jac...
8485               1  dan amd you have realy n

In [3]:
type(label_bullying)
import numpy as np
label_bullying=np.array(label_bullying)
type(label_bullying)

numpy.ndarray

In [4]:
#lowercase
list_text= [text.lower() for text in list_text]
print(list_text[4])
#number
list_text=[re.sub(r'\d+','',text) for text in list_text]
print(list_text[0])
#remove symbols [!”#$%&’()*+,-./:;<=>?@[\]^_`{|}~]
print(list_text[279])
list_text= [text.translate(str.maketrans('','',string.punctuation)) for text in list_text]
print(list_text[279])
#remove single characters ?
print(list_text[7])
list_text=[re.sub(r'\s+[a-zA-Z]\s+',' ',text) for text in list_text]
print(list_text[7])
#remove single characters
print(list_text[1])
list_text=[re.sub(r'\b[a-zA-Z]\b',' ',text) for text in list_text]
print(list_text[1])
#remove double characters
print(list_text[1])
list_text=[re.sub(r'\b[a-zA-Z][a-zA-Z]\b',' ',text) for text in list_text]
print(list_text[1])
# Substituting multiple spaces with single space
list_text = [re.sub(r'\s+', ' ', text, flags=re.I) for text in list_text]
print(list_text[1])
#remove white space
list_text = [text.strip() for text in list_text]
print(list_text[0])
list_text

well damn!! where have you been when i have needed you 'mother time'
yeah i got  backups for all that. i just hate when that happen. i been strugglin for a week now...handle that tho
haha don't hate on my mad skills.
haha dont hate on my mad skills
haha fuck i wish i was there 
haha fuck wish was there 
i hate using my bb  but love my iphone havent tried the new bb my bb is provided by my corp dont get to pick which model
  hate using my bb  but love my iphone havent tried the new bb my bb is provided by my corp dont get to pick which model
  hate using my bb  but love my iphone havent tried the new bb my bb is provided by my corp dont get to pick which model
  hate using      but love   iphone havent tried the new         provided     corp dont get   pick which model
 hate using but love iphone havent tried the new provided corp dont get pick which model
yeah got backups for all that just hate when that happen been strugglin for week nowhandle that tho


['yeah got backups for all that just hate when that happen been strugglin for week nowhandle that tho',
 'hate using but love iphone havent tried the new provided corp dont get pick which model',
 'wow lol sounds like lot piss then hehehe',
 'not damn thangthe typical rap beef one person worrying about what the next doing and the other respondin etc etc',
 'well damn where have you been when have needed you mother time',
 'watching without trace toohate when miss the minutes when the person disappears',
 'which they most the timep dont hate them either wanted one oncebut figured out couldnt live myself',
 'haha fuck wish was there',
 'paranoid wack fuckthe best song definitely bad news',
 'london hate thee enjoy yourselves',
 'lollipop lolipopoh loli loli loliduh duh dum dum dum pop damn bad cheeeering people',
 'you pretty sure angels ass fake too huh hated that wont answer cuz conroversy good shit that means fake',
 'hear that hate charging',
 'that sucks furnace started making funny

In [5]:
#tokenize
tokenizer = nltk.tokenize.TreebankWordTokenizer()
list_tokens = [tokenizer.tokenize(text) for text in list_text]
print(len(list_tokens))
print(list_tokens)

8492
[['yeah', 'got', 'backups', 'for', 'all', 'that', 'just', 'hate', 'when', 'that', 'happen', 'been', 'strugglin', 'for', 'week', 'nowhandle', 'that', 'tho'], ['hate', 'using', 'but', 'love', 'iphone', 'havent', 'tried', 'the', 'new', 'provided', 'corp', 'dont', 'get', 'pick', 'which', 'model'], ['wow', 'lol', 'sounds', 'like', 'lot', 'piss', 'then', 'hehehe'], ['not', 'damn', 'thangthe', 'typical', 'rap', 'beef', 'one', 'person', 'worrying', 'about', 'what', 'the', 'next', 'doing', 'and', 'the', 'other', 'respondin', 'etc', 'etc'], ['well', 'damn', 'where', 'have', 'you', 'been', 'when', 'have', 'needed', 'you', 'mother', 'time'], ['watching', 'without', 'trace', 'toohate', 'when', 'miss', 'the', 'minutes', 'when', 'the', 'person', 'disappears'], ['which', 'they', 'most', 'the', 'timep', 'dont', 'hate', 'them', 'either', 'wanted', 'one', 'oncebut', 'figured', 'out', 'couldnt', 'live', 'myself'], ['haha', 'fuck', 'wish', 'was', 'there'], ['paranoid', 'wack', 'fuckthe', 'best', 'song

In [6]:
#stopwords
stop_words = set(stopwords.words('english'))  #nltk file
with open("stopwords.txt") as file:
    for line in file:
        stop_words1=line.split(",")  #opensource
      
tmp=[]
tmplist=[]
for text in list_tokens:
    for i in text:
        if (not i in stop_words) and (not i in stop_words1):
            tmp.append(i)
    tmplist.append(tmp)
    tmp=[]
list_tokens=tmplist
print(list_tokens) 

[['yeah', 'backups', 'hate', 'happen', 'week'], ['hate', 'using', 'love', 'iphone', 'havent', 'tried', 'new', 'provided', 'corp', 'dont', 'pick', 'model'], ['wow', 'lol', 'sounds', 'lot', 'piss', 'hehehe'], ['damn', 'thangthe', 'typical', 'rap', 'beef', 'one', 'person', 'worrying', 'next', 'respondin'], ['well', 'damn', 'needed', 'mother', 'time'], ['watching', 'without', 'trace', 'toohate', 'miss', 'minutes', 'person', 'disappears'], ['timep', 'dont', 'hate', 'wanted', 'one', 'oncebut', 'figured', 'couldnt', 'live'], ['haha', 'fuck', 'wish'], ['paranoid', 'wack', 'fuckthe', 'best', 'song', 'definitely', 'bad', 'news'], ['london', 'hate', 'thee', 'enjoy'], ['lollipop', 'lolipopoh', 'loli', 'loli', 'loliduh', 'dum', 'dum', 'dum', 'pop', 'damn', 'bad', 'cheeeering', 'people'], ['pretty', 'sure', 'angels', 'ass', 'fake', 'huh', 'hated', 'wont', 'answer', 'cuz', 'conroversy', 'good', 'shit', 'means', 'fake'], ['hear', 'hate', 'charging'], ['sucks', 'furnace', 'started', 'making', 'funny', 

In [7]:
#lemmetizing

lemmatizer= nltk.stem.WordNetLemmatizer()
tmp=[]
tmpl=[]
for i in range(len(list_tokens)):
    for word in list_tokens[i]:
        tmp.append( lemmatizer.lemmatize(word,'n'))
    tmpl.append(tmp)
    tmp=[]
list_tokens=tmpl
#list_tokens
                   
                   
list_tokens=[" ".join(lemmatizer.lemmatize(word,'v') for word in list_tokens[i]) for i in range(len(list_tokens))]

#print(type(list_tokens))
print(list_tokens)

['yeah backup hate happen week', 'hate use love iphone havent try new provide corp dont pick model', 'wow lol sound lot piss hehehe', 'damn thangthe typical rap beef one person worry next respondin', 'well damn need mother time', 'watch without trace toohate miss minute person disappear', 'timep dont hate want one oncebut figure couldnt live', 'haha fuck wish', 'paranoid wack fuckthe best song definitely bad news', 'london hate thee enjoy', 'lollipop lolipopoh loli loli loliduh dum dum dum pop damn bad cheeeering people', 'pretty sure angel as fake huh hat wont answer cuz conroversy good shit mean fake', 'hear hate charge', 'suck furnace start make funny noise day panic attack dont deal cold well', 'damn straight', 'hate job', 'lol proud inability deal cold hate treadmill much cold', 'hate up down lol seanzageek pretty awesome amd hasnt meet release date alone beat age', 'awesome hate update bios lol', 'look good competitor wouldnt touch personally hate symbian nokia software bitch lol

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect= CountVectorizer()
x_count= count_vect.fit_transform(list_tokens)
x_count.shape


(8492, 12330)

In [9]:
#Tfidf
from sklearn.feature_extraction.text import TfidfTransformer  
tfidfcon = TfidfTransformer()
xtfidf=tfidfcon.fit_transform(x_count)


xtfidf.shape

(8492, 12330)

In [10]:
#Tfidf
from sklearn.feature_extraction.text import TfidfVectorizer  
tfidfconverter = TfidfVectorizer(max_features=15000, min_df=3, max_df=0.7) 
corpus=list_tokens
x = tfidfconverter.fit_transform(corpus)

feature_names=tfidfconverter.get_feature_names()
feature_vectors=x.toarray()
print(len(feature_names))
print(feature_vectors)
x.shape

2984
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


(8492, 2984)

In [11]:
#saving as vectorizer pickle
import pickle
with open('vectorizer.pickle', 'wb') as picklefile:  
    pickle.dump(tfidfconverter,picklefile)
print("done")

done


In [12]:
#train test divide
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(feature_vectors, label_bullying, test_size=0.3, random_state=0) 
print("done divide!")
x_train.shape


done divide!


(5944, 2984)

In [13]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(x_train, y_train)
print("done Successfully")

done Successfully


In [14]:
#naivebayes
predicted = clf.predict(x_test)
print("done")
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,predicted))  
print(classification_report(y_test,predicted))  
print("Acuracy: ",accuracy_score(y_test, predicted)*100) 

done
[[957 322]
 [481 788]]
             precision    recall  f1-score   support

          0       0.67      0.75      0.70      1279
          1       0.71      0.62      0.66      1269

avg / total       0.69      0.68      0.68      2548

Acuracy:  68.4850863422292


In [15]:
'''from sklearn  import svm
clf_svm=svm.SVC().fit(x_train, y_train)
print("done Successfully")'''

'from sklearn  import svm\nclf_svm=svm.SVC().fit(x_train, y_train)\nprint("done Successfully")'

In [16]:
from sklearn.linear_model import SGDClassifier as s
svmclf= s(loss='hinge', penalty='l2',alpha=1e-3,random_state=42,max_iter=5,tol=None)
svmclf=svmclf.fit(x_train, y_train)
print("done Successfully")



done Successfully


In [17]:
#svm

predicted_svm = svmclf.predict(x_test)
print("done")
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,predicted_svm))  
print(classification_report(y_test,predicted_svm))  
print("Acuracy: ",accuracy_score(y_test, predicted_svm)*100) 

done
[[1117  162]
 [ 609  660]]
             precision    recall  f1-score   support

          0       0.65      0.87      0.74      1279
          1       0.80      0.52      0.63      1269

avg / total       0.72      0.70      0.69      2548

Acuracy:  69.74097331240189


In [18]:
#saving as pickle
import pickle
with open('cyberguard_classifier.pickle', 'wb') as picklefile:  
    pickle.dump(svmclf,picklefile)
print("done")

done


In [19]:
#loding pickle
'''import pickle
with open('cyberguard_classifier', 'rb') as training_model:  
    model = pickle.load(training_model)
print("model loaded")
y_pred = model.predict(x_test)
print("prediction done")
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print("Acuracy: ",accuracy_score(y_test, y_pred)*100)'''

'import pickle\nwith open(\'cyberguard_classifier\', \'rb\') as training_model:  \n    model = pickle.load(training_model)\nprint("model loaded")\ny_pred = model.predict(x_test)\nprint("prediction done")\nfrom sklearn.metrics import classification_report, confusion_matrix, accuracy_score\n\nprint(confusion_matrix(y_test,y_pred))  \nprint(classification_report(y_test,y_pred))  \nprint("Acuracy: ",accuracy_score(y_test, y_pred)*100)'

In [20]:
#linear regression
from sklearn import linear_model
reg = linear_model.LogisticRegression()
reg.fit(x_train, y_train)
print("done Successfully")

done Successfully


In [21]:
#linear regression
predicted_reg = reg.predict(x_test)
print("done")
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,predicted_reg))  
print(classification_report(y_test,predicted_reg))  
print("Acuracy: ",accuracy_score(y_test, predicted_reg)*100) 

done
[[922 357]
 [459 810]]
             precision    recall  f1-score   support

          0       0.67      0.72      0.69      1279
          1       0.69      0.64      0.67      1269

avg / total       0.68      0.68      0.68      2548

Acuracy:  67.97488226059654


In [22]:
n=["you are just wonderful and stupid"]
#n=["you are good"]
tfidfnew= tfidfconverter.transform(n)
prednew= clf.predict(tfidfnew)
if prednew==1:
    print("Bullying")
elif prednew==0:
    print("Not Bullying")



Bullying
